// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250607215822_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Avocado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Avocados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yüksek yağ içeriği ve kremsi dokusu ile bilinen, en popüler avokado çeşidi.",
                            ImageUrl = "/images/hass.jpg",
                            IsAvailable = true,
                            LongDescription = "Hass avokadosu, koyu yeşilden siyaha dönen pürüzlü kabuğu ile kolayca tanınır. Eti yüksek yağ içeriği nedeniyle son derece kremsi ve lezzetlidir. Olgunlaştıkça kabuk rengi koyulaşır ve ete hafif baskı uygulandığında yumuşaksa, yemeye hazır demektir. Hass, tüm dünyada en yaygın yetiştiriciliği yapılan avokado çeşididir ve özellikle guacamole yapmak için mükemmeldir.",
                            Name = "Hass Avokado",
                            Price = 29.99m,
                            Type = "Hass"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yumuşak dokusu ve hafif tatlı tadı ile bilinen orta boyutlu avokado çeşidi.",
                            ImageUrl = "/images/fuerte.jpg",
                            IsAvailable = true,
                            LongDescription = "Fuerte avokadosu, Hass'tan daha büyük olan, parlak yeşil kabuğa sahip armut şeklinde bir meyvedir. Adını İspanyolca \"güçlü\" kelimesinden alır ve soğuk iklimlere dayanıklılığıyla bilinir. Daha az yağlı olmasına rağmen, zengin kremsi tadıyla sandviçler, salatalar ve smoothie'ler için mükemmel bir seçimdir. Olgunlaştığında ete hafifçe bastırıldığında yumuşak hissedilir, ancak rengi yeşil kalır.",
                            Name = "Fuerte Avokado",
                            Price = 34.99m,
                            Type = "Fuerte"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Daha açık yeşil rengi ve su gibi dokusu ile tanınan düşük yağlı avokado.",
                            ImageUrl = "/images/zutano.jpg",
                            IsAvailable = true,
                            LongDescription = "Zutano avokadosu, parlak, açık yeşil kabuğu ve armut şekli ile tanınır. Daha düşük yağ içeriği nedeniyle, eti daha az kremsi ve hafif sulu bir dokuya sahiptir. Hafif tatlı tadı vardır ve özellikle yemeklerde garnitür olarak veya hafif bir lezzet isteyenler için idealdir. Soğuğa dayanıklı olduğu için daha serin iklimlerde yetiştirilir ve genellikle kış aylarında bulunur.",
                            Name = "Zutano Avokado",
                            Price = 27.99m,
                            Type = "Zutano"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İnce, kolay soyulabilen kabuğu ve orta büyüklükteki çekirdeğiyle bilinen avokado türü.",
                            ImageUrl = "/images/bacon.jpg",
                            IsAvailable = true,
                            LongDescription = "Bacon avokadosu, adını avokado yetiştiricisi James Bacon'dan alan, orta boy meyveli bir türdür. İnce, kolay soyulabilen parlak yeşil kabuğa ve orta büyüklükte bir çekirdeğe sahiptir. Eti sarı-yeşil renkte, kremsi bir dokuya sahip olup, hafif tatlı bir tadı vardır. Hass'a göre daha az yağlı ancak Zutano'dan daha kremsidir. Soğuğa dayanıklı olduğundan, kış aylarında bulunabilir ve salatalarda, sandviçlerde veya doğrudan tüketim için idealdir.",
                            Name = "Bacon Avokado",
                            Price = 32.99m,
                            Type = "Bacon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
